/*******************************************************************************
 * CLI - A simple command line interface.
 * Copyright (C) 2016 Daniele Pallastrelli
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef COLORPROFILE_H_
#define COLORPROFILE_H_

#include "rang.h"

namespace cli
{
namespace ColorProfile
{
#if defined(CLI_COLOR)
	//constexpr auto PromptColor = rang::fgB::green;
	constexpr auto PromptColor = rang::fg::green;
	constexpr auto PromptStyle = rang::style::bold;
	//constexpr auto InputColor = rang::fg::yellow;
	//constexpr auto InputColor = rang::fg::magenta;
	constexpr auto InputColor = rang::fgB::gray;
	//constexpr auto InputColor = rang::fg::cyan;
	constexpr auto ForceColor = rang::control::forceColor;
	constexpr auto Reset = rang::style::reset;
#else
	constexpr auto PromptColor = rang::style::reset;
	constexpr auto PromptStyle = rang::style::reset;
	constexpr auto InputColor = rang::style::reset;
	constexpr auto ForceColor = rang::control::forceColor;
	constexpr auto Reset = rang::style::reset;
#endif
}
} // namespace

#endif // COLORPROFILE_H_


