/*******************************************************************************
 * Copyright (C) 2016 Daniele Pallastrelli
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef COMPILER_CXX0X_H_
#define COMPILER_CXX0X_H_

// gcc with -std=c++0x
#ifdef __GXX_EXPERIMENTAL_CXX0X__
    #define COMPILER_HAS_CXX0X
#endif

// the compiler declares it's C++11 standard compliant
#if defined(__cplusplus) && (__cplusplus  > 199711L)
    #define COMPILER_HAS_CXX0X
#endif

// if the compiler defines nullptr_t, it's C++11 compliant (is it true?)
#if defined(nullptr_t)
    #define COMPILER_HAS_CXX0X
#endif

// visual studio >= 2010
#if defined(_MSC_VER) && (_MSC_VER >= 1600)
    #define COMPILER_HAS_CXX0X
#endif

// explicit use of boost
#ifdef COMPILER_FORCE_USE_BOOST
    #undef COMPILER_HAS_CXX0X
#endif

// explicit use of C++0x
#ifdef COMPILER_FORCE_USE_STD
    #define COMPILER_HAS_CXX0X
#endif


// using the right headers and namespace
#ifdef COMPILER_HAS_CXX0X
    #include <memory>
    #include <type_traits>
    #include <functional>
    #include <unordered_map>
    #include <thread>
    #include <mutex>
    namespace cxx0x = std;
    namespace cxx0x_ph = std::placeholders;
#else
    #include <boost/shared_ptr.hpp>
    #include <boost/scoped_ptr.hpp>
    #include <boost/weak_ptr.hpp>
    #include <boost/bind.hpp>
    #include <boost/type_traits.hpp>
    #include <boost/function.hpp>
    #include <boost/make_shared.hpp>
    #include <boost/unordered_map.hpp>
    #include <boost/thread.hpp>
    namespace cxx0x = boost;
    #define cxx0x_ph
    #define unique_ptr scoped_ptr
    #define nullptr 0
#endif


#endif
